In [1]:
# 一维数组
import numpy as np

In [25]:
# 创建一个一维数组
my_array = np.array(5)
# 创建一个全部都是0的一维数组
zero_array = np.zeros(5)
# 创建一个全部都是1的一维数组
one_array = np.ones((2,2))
# 获取随机数组
random_array = np.random.random((2,2))
# 相当于range
arange_array = np.arange(5)
arange_array

array([0, 1, 2, 3, 4])

In [21]:
# numpy 的数组操作
a = np.array([[1.0,2.0],[3.0,4.0]])
b = np.array([[5.0,6.0],[7.0,8.0]])
sum = a + b
difference = a - b
product = a * b
quotient = a / b
# 矩阵乘法
matrix_product = a.dot(b) # 19 = 1 * 5 + 2 * 7   22 = 1 * 6 + 2 * 8
matrix_product

array([[19., 22.],
       [43., 50.]])

In [38]:
# 多维数组
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])


print(a[0,1:4])
print(a[1:4,0])
print(a[::2,::2])
print(a[:, 1])

[12 13 14]
[16 21 26]
[[11 13 15]
 [21 23 25]
 [31 33 35]]
[12 17 22 27 32]
4


In [40]:
# 数组属性
print(type(a))  # <class 'numpy.ndarray'>
print(a.dtype) # 类型int32
print(a.size) # 数组所有元素 25
print(a.shape) # 数组的结构 5 * 5
print(a.itemsize)  # 属性是每个项占用的字节数 这个是int 32 所以 32 / 8
print(a.ndim)  # 数组的维度
print(a.nbytes) # 属性是数组中的所有数据消耗掉的字节数


<class 'numpy.ndarray'>
int32
25
(5, 5)
4
2
100
