### python

#### 快速排序

In [1]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


### numpy

#### 数组（array）

In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

(2, 3)
1 2 4


In [10]:
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2),7)
d = np.eye(2)
e = np.random.random((2,2))
print(a)
print(b)
print(c)
print(d)
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.94167461 0.25431189]
 [0.31429585 0.64672767]]


#### 数组索引

In [13]:
# 切片
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2,1:3]
print(a[0,1])
b[0,0] = 99
print(a[0,1])

2
99


In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :] 
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [19]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b]) 
a[np.arange(4), b] += 10
print(a)

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [22]:
# 布尔数组索引: 
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(a[bool_idx]) 
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


#### 数据类型

In [26]:
x = np.array([1, 2]) 
print(x.dtype)
y = np.array([1.0,2.0])
print(y.dtype)
z = np.array([0,1,2],dtype=np.int64)
print(z.dtype)

int32
float64
int64


#### 数组中的数学

In [29]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x-y)
print(np.subtract(x,y))
print(x * y)
print(np.multiply(x,y))
print(x / y)
print(np.divide(x,y))
print("------------------------")
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
------------------------a
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [32]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])




v = np.array([9,10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))
# 1 * 9 + 2 * 10
# 3 * 9 +  4 * 10

print(x.dot(y))
print(np.dot(x, y))
# 1 * 5 + 2 * 7
# 2 * 5 + 2 * 7 
# 3 * 6 + 3 * 8
# 4 * 6 + 4 * 8

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [33]:
x = np.array([[1,2],[3,4]])
print(np.sum(x)) 
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [34]:
x = np.array([[1,2], [3,4]])
print(x) 
print(x.T) 
v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


#### 广播

In [35]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) 
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)  

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [37]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  
print(vv)  
y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### scipy

#### 图像操作

In [4]:
from scipy import misc 

In [8]:

import imageio
from matplotlib import pyplot as plt 
im2 = imageio.imread('./cat.jpg')
print(im2.dtype)
print(im2.size)
print(im2.shape)
plt.show()
print(im2)
imageio.imwrite('./imageio.png',im2)

uint8
297600
(400, 248, 3)
[[[132 128 116]
  [155 151 139]
  [181 175 161]
  ...
  [ 78  68  43]
  [ 76  65  43]
  [ 64  53  31]]

 [[134 130 118]
  [152 149 134]
  [177 171 157]
  ...
  [ 75  65  40]
  [ 72  61  39]
  [ 62  51  29]]

 [[140 134 120]
  [151 145 131]
  [174 168 154]
  ...
  [ 71  61  36]
  [ 66  59  33]
  [ 59  52  26]]

 ...

 [[115 145  75]
  [107 136  69]
  [106 135  69]
  ...
  [113 101  79]
  [106  94  72]
  [103  91  67]]

 [[107 134  67]
  [110 139  72]
  [109 138  72]
  ...
  [112  97  76]
  [109  94  73]
  [103  88  67]]

 [[124 151  84]
  [116 143  76]
  [111 140  76]
  ...
  [ 91  76  57]
  [ 89  74  53]
  [ 86  71  50]]]
